set(CLANG_ARCH arm)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_OSX_ARCHITECTURES armv7)

set(CMAKE_C_SIZEOF_DATA_PTR 4)
set(CMAKE_CXX_SIZEOF_DATA_PTR 4)

include("${CMAKE_CURRENT_LIST_DIR}/ios.cmake")
