set(CLANG_ARCH arm64)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_OSX_ARCHITECTURES arm64)

set(CMAKE_C_SIZEOF_DATA_PTR 8)
set(CMAKE_CXX_SIZEOF_DATA_PTR 8)

include("${CMAKE_CURRENT_LIST_DIR}/ios.cmake")
