SET(CMAKE_SYSTEM_NAME iOS)

set(CMAKE_INSTALL_NAME_TOOL /opt/cctools/bin/install_name_tool)
set(CMAKE_OBJCXX_COMPILER ${CMAKE_CXX_COMPILER})
set(CMAKE_OBJC_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_MACOSX_RPATH TRUE)
set(CMAKE_LIBRARY_PATH ${CMAKE_OSX_SYSROOT}/System/Library/)
set(CMAKE_SYSTEM_FRAMEWORK_PATH ${CMAKE_LIBRARY_PATH}/Frameworks/)

set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)

set(CMAKE_SHARED_LIBRARY_PREFIX "lib")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".dylib")
set(CMAKE_SHARED_MODULE_PREFIX "lib")
set(CMAKE_SHARED_MODULE_SUFFIX ".so")
set(CMAKE_C_COMPILER_ABI ELF)
set(CMAKE_CXX_COMPILER_ABI ELF)
set(CMAKE_C_HAS_ISYSROOT 1)
set(CMAKE_CXX_HAS_ISYSROOT 1)
set(CMAKE_MODULE_EXISTS 1)
set(CMAKE_DL_LIBS "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ALWAYS)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH
  "${CMAKE_FIND_ROOT_PATH}"
  "${CMAKE_OSX_SYSROOT}")

get_property( _CMAKE_IN_TRY_COMPILE GLOBAL PROPERTY IN_TRY_COMPILE )
if(NOT _CMAKE_IN_TRY_COMPILE)
	string(APPEND CMAKE_C_FLAGS_INIT " -fPIC ")
	string(APPEND CMAKE_CXX_FLAGS_INIT " -fPIC ")

	set(CCTOOLS_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS})

	string(APPEND CMAKE_MODULE_LINKER_FLAGS_INIT " ${CCTOOLS_LINKER_FLAGS} ")
	string(APPEND CMAKE_SHARED_LINKER_FLAGS_INIT " ${CCTOOLS_LINKER_FLAGS} ")
	string(APPEND CMAKE_EXE_LINKER_FLAGS_INIT " ${CCTOOLS_LINKER_FLAGS} ")
	string(APPEND CMAKE_MODULE_LINKER_FLAGS_DEBUG_INIT " ${CCTOOLS_LINKER_FLAGS} ")
	string(APPEND CMAKE_SHARED_LINKER_FLAGS_DEBUG_INIT " ${CCTOOLS_LINKER_FLAGS} ")
	string(APPEND CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT " ${CCTOOLS_LINKER_FLAGS} ")
	string(APPEND CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT " ${CCTOOLS_LINKER_FLAGS} ")
	string(APPEND CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT " ${CCTOOLS_LINKER_FLAGS} ")
	string(APPEND CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT " ${CCTOOLS_LINKER_FLAGS} ")
endif()