if(${CMAKE_OSX_ARCHITECTURES} STREQUAL "i386")
set(CMAKE_CXX_COMPILER /opt/cctools/bin/x86_64-iphonesimulator-clang++)
set(CMAKE_C_COMPILER /opt/cctools/bin/x86_64-iphonesimulator-clang)
else()
set(CMAKE_CXX_COMPILER /opt/cctools/bin/${CMAKE_OSX_ARCHITECTURES}-iphonesimulator-clang++)
set(CMAKE_C_COMPILER /opt/cctools/bin/${CMAKE_OSX_ARCHITECTURES}-iphonesimulator-clang)
endif()
if(${CMAKE_OSX_ARCHITECTURES} STREQUAL "arm64")
set(CMAKE_RANLIB /opt/cctools/bin/arm-apple-darwin11-ranlib)
set(CMAKE_AR /opt/cctools/bin/arm-apple-darwin11-ar)
else()
set(CMAKE_RANLIB /opt/cctools/bin/x86_64-apple-darwin11-ranlib)
set(CMAKE_AR /opt/cctools/bin/x86_64-apple-darwin11-ar)
endif()
set(CMAKE_EXE_LINKER_FLAGS /opt/cctools/darwin/libclang_rt.iossim.a)
set(CMAKE_OSX_SYSROOT /opt/cctools/sdk/iPhoneSimulator.sdk)

include("${CMAKE_CURRENT_LIST_DIR}/ios-base.cmake")
