SET(CMAKE_SYSTEM_NAME iOS)

set(CMAKE_OSX_ARCHITECTURES x86_64)
set(CLANG_ARCH x86_64)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_SIZEOF_DATA_PTR 8)
set(CMAKE_CXX_SIZEOF_DATA_PTR 8)

include("${CMAKE_CURRENT_LIST_DIR}/iossim.cmake")