SET(CMAKE_SYSTEM_NAME iOS)

set(CMAKE_OSX_ARCHITECTURES i386)
set(CLANG_ARCH i386)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(CMAKE_C_SIZEOF_DATA_PTR 4)
set(CMAKE_CXX_SIZEOF_DATA_PTR 4)

include("${CMAKE_CURRENT_LIST_DIR}/iossim.cmake")
