set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_ENV_PASSTHROUGH PATH)
set(VCPKG_C_FLAGS   "-D_WIN32_WINNT=0x0400 -mno-sse2 -march=i486")
set(VCPKG_CXX_FLAGS "-D_WIN32_WINNT=0x0400 -mno-sse2 -march=i486")

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
